# Generated by Django 3.2.13 on 2022-06-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Daftar mata Kuliah'},
        ),
        migrations.AlterModelOptions(
            name='tugas',
            options={'verbose_name': 'Tugas', 'verbose_name_plural': 'Daftar Tugas'},
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
